### PR TITLE
Switch to section/h3 markup

### PR DESCRIPTION
**Pull request by BigBlueHat**
I couldn't tell if the orange box thing was a hold-over from the original or if it was intended for this version. I really wanted the best practices in the sidebar, so that was my main objective.

Do let me know, though, if this should be done differently.

Cheers!
🎩

### CODE REVIEW

**Comment by gkellogg** [comment]
We need to get pr-preview set up for this repo.

**Comment by gkellogg** [comment]
The `class="practice"` is a feature of ReSpec for marking up best practices. I'm not sure we need it, or we could use it and style to taste.

* [practice](https://github.com/w3c/respec/wiki/practice)
* [practicedesc](https://github.com/w3c/respec/wiki/practicedesc)
* [practicelab](https://github.com/w3c/respec/wiki/practicelab)

**Comment by BigBlueHat** [comment]
@gkellogg do you know of other specs (off-hand) that use these classes?

**Comment by BigBlueHat** [comment]
@gkellogg been thinking through the use of those styles, and I believe they're intended for inline best practices and not for whole documents that are exclusively best practices.

Do you mind if we ignore those class names for now? I don't really want to restyle them (or hide their styling) as that rather defeats the purpose. 😃

**Comment by gkellogg** [comment]
Whatever you think is best.

**Pull request merged**
